const {w: t} = require('@iondv/i18n');

module.exports = {
	'templates.default.content.title': t('Home'),
	'templates.default.errors.404.title': t('Page not found'),
	'templates.default.errors.404.detail': t('We could not find page you are looking for.'),
	'templates.default.errors.500.title': t('Server error'),
	'templates.default.errors.500.message': t('Something went wrong'),
	'templates.default.errors.500.detail': t('We are working on fixing this error right now.'),
	'templates.default.errors.search.input': t('Search...'),
	'templates.default.layout.footer.version': t('Version'),
	'templates.default.layout.footer.copyright': t('Copyright'),
	'templates.default.layout.header.signOut': t('Exit'),
	'templates.default.layout.header.userAvatar': t('User avatar'),
	'templates.default.layout.header.adminPanel': t('admin panel'),
	'templates.default.view.404.message': t('No reports set up for this link'),
	'templates.default.view.exportTools.export': t('Export'),
	'templates.default.view.exportTools.download': t('Download export results'),
	'templates.default.view.exportTools.print': t('Print'),
	'templates.default.view.paramInput.option.no': t('none'),
	'templates.default.view.report.title': t('Builds journal'),
	'templates.default.view.report.source': t('Data source'),
	'templates.default.view.report.sourceDate': t('Last build date'),
	'templates.default.view.report.refreshing': t('refreshing'),
	'templates.default.view.report.refreshInfo': t('Reload data source'),
	'templates.default.view.report.prepareInfo': t('Prepare data source'),
	'templates.default.view.report.noPreparedInfo': t('Data source not ready'),
	'templates.default.view.report.loading': t('Loading...'),
	'templates.default.view.report.apply': t('Apply'),
	'templates.default.view.report.tableFilters': t('Table filters'),
	'templates.default.view.report.options.no': t('no'),
	'templates.default.view.report.script.loading': t('Data source is preparing'),
	'templates.default.view.report.script.done': t('Data mine build complete.'),
	'templates.default.view.report.script.started': t('Data mine build started.'),
	'templates.default.view.report.script.error': t('Failed to start data mine build.'),
	'templates.default.view.sheet.proceed': t('Proceed'),
	'templates.default.view.userFilter.title': t('Report filter'),
	'templates.default.view.userFilter.select': t('Select filter...'),
	'templates.default.view.userFilter.reset': t('Reset filter'),
	'templates.default.view.userFilter.input': t('Specify filter name...'),
	'templates.default.view.userFilter.saveFilter': t('Save'),
	'templates.default.view.userFilter.saveFilterTitle': t('Save filter'),
	'templates.default.view.userFilter.removeFilter': t('Delete filter'),
	'templates.default.view.userFilter.applyFilter': t('Apply filter')
};
